### PR TITLE
🔧 Add migration scripts

### PR DESCRIPTION
**Pull request by dankolbman**
Adds scripts to migrate buckets under old configuration to new encrypted, versioned, replicated buckets.

### CODE REVIEW

**Comment by dankolbman** [comment]
I've copied bucket `kf-study-us-east-1-prd-sd-46sk55a3` and am working through validation before deleting.

###$ Check that the number of objects in the replicated bucket equals the number of (latest) objects in the study bucket
```
$ cat kf-study-us-east-1-prd-sd-46sk55a3/inventory.txt | grep true, | wc -l
16258
$ cat kf-study-us-west-2-prd-sd-46sk55a3-dr/inventory.txt | wc -l
16266
$ cat kf-study-us-west-2-prd-sd-46sk55a3-dr/inventory.txt | grep true, |  wc -l
16257
```

Looks like there may be one object that was not backed up

```
$ comm -3 <(sort kf-study-us-east-1-prd-sd-46sk55a3/inventory.txt | grep true,) <(sort kf-study-us-west-2-prd-sd-46sk55a3-dr/inventory.txt | grep true,)
true,u7mScWri1Y5L3_jjaDxPNZv.Vd.MUMcL,harmonized/family-variants/
```

It looks like it's just a directory, so not important

**Comment by dankolbman** [comment]
```
ere are kf-study-us-east-1-prd-sd-46sk55a3/inventory.txt object versions in kf-study-us-east-1-prd-sd-46sk55a3
There are 16257 unique files
There are 16257 files with at least 2 versions
There are 15471 files with a null version id
!! WARNING!!!!!!!!!!!
!! The above numbers are not in agreement.
!! This could mean that some files were not copied or old versions were already deleted.
!! Please make sure you want to continue
```
It seems that some objects have been uploaded since we turned on versioning and thus won't be deleted as part of this strategy.
We could either:
1) Delete all objects that are in the study bucket, but not in the replication bucket and are not the latest version
2) Leave these files in as duplicates

**Comment by alubneuski** [comment]
I vote for 1). From I can see every object has at least one version that is not null and few have 4 versions.

**Comment by dankolbman** [comment]
Copied over:
- `kf-study-us-east-1-prd-sd-6fpyjqbr`

Waiting for confirmation on deletion logic before cleaning up dupes

**Pull request merged**
